## Importing libraries

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import zipfile
import os

# Step 1: Set the path to the unzipped dataset directory
unzip_dir = r'C:\Users\HP\Desktop\Plant_Disease_Dataset'

# Step 2: Update directory paths for the 'train' and 'valid' folders
train_dir = os.path.join(unzip_dir, 'train')  # Path to the training images folder
valid_dir = os.path.join(unzip_dir, 'valid')  # Path to the validation images folder

# Step 3: Create training and validation datasets
training_set = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

validation_set = tf.keras.utils.image_dataset_from_directory(
    valid_dir,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)
# Build the model

from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.models import Sequential

# Create a sequential model
model = Sequential()

model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=[128, 128, 3]))
model.add(Conv2D(filters=32, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))  # Corrected 'stride' to 'strides'

model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))  # Corrected 'stride' to 'strides'

model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))  # Corrected 'stride' to 'strides'

model.add(Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=256, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))  # Corrected 'stride' to 'strides'

model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=512, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=2, strides=2))  # Corrected 'stride' to 'strides'

model.add(Dropout(0.25))

model.add(Flatten())

model.add(Dense(units=1500, activation='relu'))

model.add(Dropout(0.4))

# Output Layer
model.add(Dense(units=38, activation='softmax'))

# Compiling model
from tensorflow.keras.optimizers import Adam

model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

## Training model
training_history= model.fit(x=training_set,validation_data=validation_set,epochs=10)

## Evaluation of model
# evaluate model on training set

train_loss,train_acc = model.evaluate(training_set)

#model on validation set
val_loss,val_acc = model.evaluate(training_set)

##Model saving
model.save("trained_model.keras")
training_history.history


#Record history in json
#Recording History in json
import json
with open('training_hist.json','w') as f:
  json.dump(training_history.history,f)

##Visualize accuracy
epochs = [i for i in range(1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='green',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel('No. of Epochs')
plt.title('Visualization of Accuracy Result')
plt.legend()
plt.show()













In [10]:
### other metrics for evaluation
class_name = validation_set.class_names
class_name


['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_

In [7]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=1,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)


Found 17572 files belonging to 38 classes.


In [10]:
import tensorflow as tf

# Load the pre-trained model from the .keras file
model = tf.keras.models.load_model("trained_model.keras")

# Perform prediction on the test set
y_pred = model.predict(test_set)

# Get the predicted categories (indices of the highest probability class)
predicted_categories = tf.argmax(y_pred, axis=1)

# Print the predicted categories
print(predicted_categories)






17572/17572 ━━━━━━━━━━━━━━━━━━━━ 254s 14ms/step
tf.Tensor([ 0  0  0 ... 37 37 37], shape=(17572,), dtype=int64)


In [12]:
true_categories = tf.concat([y for x, y in test_set], axis=0)

# Print the true categories
print(true_categories)

tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]], shape=(17572, 38), dtype=float32)


In [29]:
true_categories = tf.concat([y for x, y in test_set], axis=1)

# Print the true categories
print(true_categories)

tf.Tensor([[1. 0. 0. ... 0. 0. 1.]], shape=(1, 667736), dtype=float32)
